#
# Spec file generated by kdist version v0.0.4
#
Name:          kernel-desktop
Summary:       The Linux Kernel for Mandriva systems
License:       GPLv2
Version:       2.6.39.1
Release:       %mkrel 1.1
URL:           http://www.kernel.org
Source:        kernel-2.6.39.1-1.1-desktop.tar.bz2
ExclusiveArch: %ix86 x86_64 
BuildRoot:     %{_tmppath}/%{name}-%{PACKAGE_VERSION}-root
AutoReqProv:   no

%global __debug_package 1
%define debug_package %{nil}
%define __check_files %{nil}
%ifarch %ix86 x86_64
%define asmarch x86
%define bzImage arch/x86/boot/bzImage
%endif

Summary:       The Linux Kernel for Mandriva systems
Provides:      kernel = 2.6.39.1.1.1
Provides:      kernel-desktop = 2.6.39.1.1.1
Group:         System/Kernel and hardware

%description
The Linux Kernel, the operating system core itself

%package devel
Summary:       The minimal Linux Kernel for building kernel modules
Provides:      kernel-devel = 2.6.39.1.1.1
Provides:      kernel-desktop-devel = 2.6.39.1.1.1
BuildRequires: rsync

%description -n kernel-desktop-devel
This package provides kernel headers, makefiles and a couple
of others files sufficient to build external kernel modules.

%package debuginfo
Summary:       The debug information for kernel-desktop
Provides:      kernel-debuginfo = 2.6.39.1.1.1
Provides:      kernel-desktop-debuginfo = 2.6.39.1.1.1

%description -n kernel-desktop-debuginfo
This package provides the kernel's debug information required
by some binary object tools like kgdb, perf, etc...

%prep
%setup -q -n 2.6.39.1-1.1-desktop

%build
make defconfig
make -s kernelrelease
test $(make -s kernelrelease) = 2.6.39.1-1.1-desktop
make %{?_smp_mflags}

%install
make -s INSTALL_MOD_PATH=%{buildroot} modules_install
find %{buildroot} -name \*.ko -exec chmod u+x {} \;

mkdir -p %{buildroot}/boot
cp %{bzImage} %{buildroot}/boot/vmlinuz-2.6.39.1-1.1-desktop
cp System.map %{buildroot}/boot/System.map-2.6.39.1-1.1-desktop
cp .config    %{buildroot}/boot/config-2.6.39.1-1.1-desktop
ln -snf /usr/src/devel/2.6.39.1-1.1-desktop %{buildroot}/lib/modules/2.6.39.1-1.1-desktop/build
ln -snf build %{buildroot}/lib/modules/2.6.39.1-1.1-desktop/source

mkdir -p %{buildroot}/usr/src/devel/2.6.39.1-1.1-desktop
cat develfiles-%asmarch.list >>develfiles.list
rsync -ar --files-from=develfiles.list . %{buildroot}/usr/src/devel/2.6.39.1-1.1-desktop

%post -n kernel-desktop
/sbin/installkernel 2.6.39.1-1.1-desktop

%preun -n kernel-desktop
/sbin/installkernel -R 2.6.39.1-1.1-desktop

%postun -n kernel-desktop
/sbin/kernel_remove_initrd 2.6.39.1-1.1-desktop

%clean
rm -rf %{buildroot}

%files -n kernel-desktop
%defattr (-, root, root)
%dir /lib/modules
/lib/modules/2.6.39.1-1.1-desktop
/boot

%files -n kernel-desktop-devel
%defattr (-, root, root)
/usr/src/devel/2.6.39.1-1.1-desktop

%files -n kernel-desktop-debuginfo -f debugfiles.list
%defattr (-, root, root)

%changelog
* Tue Jul 26 2011 Franck Bui <franck.bui@mandriva.com> 2.6.39.1-1.1-desktop
Andy Whitcroft <apw@canonical.com> (1):
      UBUNTU: SAUCE: isapnp_init: make isa PNP scans occur async

Anonymous <anonymous@mandriva.com> (22):
      x86 cpufreq speedstep dothan 3
      pnp pnpbios off by default
      acpi add proc event regs
      scsi ppscsi-2.6.2
      scsi ppscsi_fixes
      scsi megaraid new sysfs name
      ide pci sis5513 965
      mpt scsi modules for VMWare's emulated
      gpu drm mach64
      gpu drm mach64 fix for changed drm_pci_alloc
      gpu drm mach64 2.6.36 buildfix
      net sis190 fix list usage
      net netfilter IFWLOG
      net netfilter IFWLOG 2.6.35 buildfix
      net netfilter IFWLOG 2.6.37 buildfix
      net netfilter psd
      net netfilter psd 2.6.35 buildfix
      include kbuild export pci_ids
      sound alsa hda_intel prealloc 4mb dmabuffer
      usb storage unusual_devs add id 2.6.37 buildfix
      media video pwc lie in proc usb devices
      media video pwc no ads in dmesg

Ben Dooks <ben-linux@fluff.org> (1):
      pci add ALI M5229 ide compatibility mode quirk

Ben Hutchings <ben@decadent.org.uk> (1):
      rndis_host: Poll status channel before control channel

Claudio Matsuoka <claudio@mandriva.com> (1):
      sound alsa hda ad1884a hp dc model

Eric Piel <eric.piel@tremplin-utc.net> (1):
      acpi dsdt initrd v0.9c 2.6.28

Franck Bui <franck.bui@mandriva.com> (7):
      kdist: give a name to the config file
      kdist: make the config name part of the localversion
      ppscsi: build fix for 2.6.39
      Revert "serial docomo F2402"
      Revert "Support a Docomo comunication card in serial module."
      gpu drm mach64 2.6.39 buildfix
      Mandriva Release v2.6.39.1-1

Go Taniguchi <go@turbolinux.co.jp> (7):
      Card bus's PCI last bus
      CLEVO M360S acpi irq workaround
      Support a Docomo comunication card in serial module.
      serial docomo F2402
      Support a Bluetooth SCO.
      Add blacklist of usb hid modules
      Change to usb storage of unusual_dev.

Herton Ronaldo Krzesinski <herton@mandriva.com.br> (12):
      x86 boot video 80x25 if break
      x86 p4_clockmod reasonable default for scaling_min_freq
      acpi dsdt initrd v0.9c fixes
      acpi video add blacklist to use vendor driver
      scsi ppscsi update for scsi_data_buffer
      scsi ppscsi mdvbz45393
      agp/intel: add new host bridge id for Q57 system
      gpu drm mach64 fixes
      gpu drm mach64 fix for changed drm_ioctl
      platform x86 add shuttle wmi driver
      bluetooth hci_usb disable isoc transfers
      fb: avoid possible deadlock caused by fb_set_suspend

Herton Ronaldo Krzesinski <herton@mandriva.com> (2):
      acpi processor M720SR limit to C2
      scsi ppscsi sg helper update

Luiz Fernando N. Capitulino <lcapitulino@mandriva.com.br> (3):
      net netfilter IFWLOG mdv
      ipt_psd: Mandriva changes
      Mandriva Linux boot logo.

Miklos Szeredi <mszeredi@suse.cz> (3):
      vfs: add i_op->open()
      vfs: export do_splice_direct() to modules
      vfs: introduce clone_private_mount()

Olaf Dabrunz <od@suse.de> (1):
      default to "power_off" when SMP kernel is used on single processo

Steve Brokenshire <sbrokenshire@xestia.co.uk> (1):
      kbuild compress kernel modules on installation

Thomas Backlund <tmb@mandriva.org> (3):
      x86 pci toshiba equium a60 assign busses
      Adapt mach64 to build with 2.6.31 series kernels
      gpu drm mach64 2.6.37 buildfix

