#
# Spec file generated by kdist version v0.0.4-18-ge9c4
#
Name:          kernel-desktop
Summary:       The Linux Kernel for Mandriva systems
License:       GPLv2
Version:       2.6.39.4
Release:       %mkrel 3.1
URL:           http://www.kernel.org
Source:        kernel-2.6.39.4-3.1+-desktop.tar.bz2
ExclusiveArch: %ix86 x86_64 
BuildRoot:     %{_tmppath}/%{name}-%{PACKAGE_VERSION}-root
AutoReqProv:   no

%global __debug_package 1
%define debug_package %{nil}
%define __check_files %{nil}
%ifarch %ix86 x86_64
%define asmarch x86
%define bzImage arch/x86/boot/bzImage
%endif

Summary:       The Linux Kernel for Mandriva systems
Provides:      kernel = 2.6.39.4.3.1
Provides:      kernel-desktop = 2.6.39.4.3.1
Group:         System/Kernel and hardware

%description
The Linux Kernel, the operating system core itself

%package devel
Summary:       The minimal Linux Kernel for building kernel modules
Provides:      kernel-devel = 2.6.39.4.3.1
Provides:      kernel-desktop-devel = 2.6.39.4.3.1
BuildRequires: rsync

%description -n kernel-desktop-devel
This package provides kernel headers, makefiles and a couple
of others files sufficient to build external kernel modules.

%package debuginfo
Summary:       The debug information for kernel-desktop
Provides:      kernel-debuginfo = 2.6.39.4.3.1
Provides:      kernel-desktop-debuginfo = 2.6.39.4.3.1

%description -n kernel-desktop-debuginfo
This package provides the kernel's debug information required
by some binary object tools like kgdb, perf, etc...

%prep
%setup -q -n 2.6.39.4-3.1+-desktop

%build
make defconfig
make -s kernelrelease
test $(make -s kernelrelease) = 2.6.39.4-3.1+-desktop
make %{?_smp_mflags}

%install
make -s INSTALL_MOD_PATH=%{buildroot} modules_install
find %{buildroot} -name \*.ko -exec chmod u+x {} \;

mkdir -p %{buildroot}/boot
cp %{bzImage} %{buildroot}/boot/vmlinuz-2.6.39.4-3.1+-desktop
cp System.map %{buildroot}/boot/System.map-2.6.39.4-3.1+-desktop
cp .config    %{buildroot}/boot/config-2.6.39.4-3.1+-desktop
ln -snf /usr/src/devel/2.6.39.4-3.1+-desktop %{buildroot}/lib/modules/2.6.39.4-3.1+-desktop/build
ln -snf build %{buildroot}/lib/modules/2.6.39.4-3.1+-desktop/source

mkdir -p %{buildroot}/usr/src/devel/2.6.39.4-3.1+-desktop
cat develfiles-%asmarch.list >>develfiles.list
rsync -ar --files-from=develfiles.list . %{buildroot}/usr/src/devel/2.6.39.4-3.1+-desktop

%post -n kernel-desktop
/sbin/installkernel 2.6.39.4-3.1+-desktop

%preun -n kernel-desktop
/sbin/installkernel -R 2.6.39.4-3.1+-desktop

%postun -n kernel-desktop
/sbin/kernel_remove_initrd 2.6.39.4-3.1+-desktop

%clean
rm -rf %{buildroot}

%files -n kernel-desktop
%defattr (-, root, root)
%dir /lib/modules
/lib/modules/2.6.39.4-3.1+-desktop
/boot

%files -n kernel-desktop-devel
%defattr (-, root, root)
/usr/src/devel/2.6.39.4-3.1+-desktop

%files -n kernel-desktop-debuginfo -f debugfiles.list
%defattr (-, root, root)

%changelog
* Tue Aug 30 2011 Franck Bui <franck.bui@mandriva.com> 2.6.39.4-3.1+-desktop
Chaoming Li <chaoming_li@realsil.com.cn> (14):
      rtlwifi: rtl8192ce: Fix LED initialization
      rtlwifi: rtl8192se: Merge def.h
      rtlwifi: rtl8192se: Merge dynamic management routines
      rtlwifi: rtl8192se: Merge firmware routines
      rtlwifi: rtl8192se: Merge hardware routines
      rtlwifi: rtl8192se: Merge led routines
      rtlwifi: rtl8192se: Merge phy routines
      rtlwifi: rtl8192se: Merge register definitions
      rtlwifi: rtl8192se: Merge rf routines
      rtlwifi: rtl8192se: Merge main (sw) routines
      rtlwifi: rtl8192se: Merge table routines
      rtlwifi: rtl8192se: Merge TX and RX routines
      rtlwifi: rtl8192se: Modify Kconfig and Makefile routines for new driver
      rtlwifi: rtl8192se: Remove need to disable ASPM

Chaoming_Li <chaoming_li@realsil.com.cn> (17):
      rtlwifi: Change efuse routines addition of RTL8192SE and RTL8192DE
      rtlwifi: Change wifi.h for rtl8192se and rtl8192de
      rtlwifi: Change base routines for addition of rtl8192se and rtl8192de
      rtlwifi: Change cam routines for addition of rtl8192se and rtl8192de
      rtlwifi: Convert core routines for addition of rtl8192se and rtl8192de
      rtlwifi: Convert pci routines for addition of rtl8192se and rtl8192de
      rtlwifi: Convert ps routines for addition of rtl8192se and rtl8192de
      rtlwifi: Convert rc routines for addition of rtl8192se and rtl8192de
      rtlwifi: Convert regulatory domain routines for addition of rtl8192se and rtl8192de
      rtlwifi: Convert usb routines for addition of rtl8192se and rtl8192de
      rtlwifi: rtl8192c-common: Convert common dynamic management routines for addition of rtl8192se and rtl8192de
      rtlwifi: rtl8192c-common: Change common firmware routines for addition of rtl8192se and rtl8192de
      rtlwifi: rtl8192c-common: Change common PHY routines for addition of rtl8192se and rtl8192de
      rtlwifi: rtl8192ce: Change hw routine for addition of rtl8192se and rtl8192de
      rtlwifi: rtl8192ce: Change sw and LED routines for addition of rtl8192se and rtl8192de
      rtlwifi: rtl8192ce: Change phy and rc routines for addition of rtl8192se and rtl8192de
      rtlwifi: rtl8192ce: Change rtl8192ce routines phy and trx and modify rtl8192cu for addition of rtl8192se and rtl8192de

Franck Bui <franck.bui@mandriva.com> (1):
      Mandriva Release v2.6.39.4-3

Larry Finger <Larry.Finger@lwfinger.net> (5):
      rtlwifi: Remove unused/unneeded variables
      rtlwifi: rtl8192ce: rtl8192cu: Fix most sparse warnings
      rtl8192se: Fix warnings from gcc 4.6.0
      rtlwifi: rtl8192se: Use write barrier when assigning ownership
      rtlwifi: rtl8192se: Synchronize IRQ after disabling it

Mike McCormack <mikem@ring3k.org> (1):
      rtlwifi: Remove set_rfpowerstate_inprogress

